project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "assets/"
    - "googledc1c84c464632aff.html"
    - "style.css"
    - "!dump/"
    - "!dump_emacs/"

website:
  title: "Kanad Pardeshi"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
