project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!dump/"
    - "!dump_emacs/"
  resources:
    - assets/**
    - "style.css"
    - "googledc1c84c464632aff.html"

website:
  title: "Kanad Pardeshi"
  description: "Personal website of Kanad Pardeshi, PhD student in Machine Learning at CMU. Research in statistical ML, online learning, and decision-making."
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: research.qmd
        text: Research
  open-graph: true
  twitter-card:
    creator: "@kanadpardeshi"
    image: "./assets/img/kanad_pardeshi_headshot.jpg"
    description: "PhD student in Machine Learning at CMU. Researching statistical ML, online learning, and decision-making."

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
