project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!dump/"
    - "!dump_emacs/"
  resources:
    - assets/**
    - "style.css"
    - "googledc1c84c464632aff.html"

website:
  title: "Kanad Pardeshi"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
